### ISSUE TITLE
加油啊，老哥。。。

### ISSUE THREAD

**Issue by adaaaaaa** [KFERMercer/luci-app-adguardhome#1]
什么时候有空做一下？？

**Comment by KFERMercer** [comment]
因为无法解决的冲突问题, adguardhome的luci页面暂停开发. 如果想自行调试, 欢迎使用[openwrt-adguardhome](https://github.com/KFERMercer/openwrt-adguardhome).

**Comment by adaaaaaa** [comment]
这个家伙已经做得不错了，复制他的吧？？🤪🤪🤪
https://github.com/rufengsuixing/luci-app-adguardhome

**Comment by KFERMercer** [comment]
不搞了 不好用
